src/BookStore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')),
    path('books/', include('books.urls')),
    path('orders/', include('orders.urls')),
    path('session/', include('session_basket.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('', include('pages.urls')),
    path('api/v1/dj-rest-auth/', include('dj_rest_auth.urls')),
    path('api/v1/dj-rest-auth/registration/', include('dj_rest_auth.registration.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.MEDIA_ROOT)

src/accounts/urls.py
from django.urls import path

from accounts import views, API_views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup-modal'),
    path('address/create/', views.AddressCreateView.as_view(), name='address-create'),
    path('address/<int:pk>/update/', views.AddressUpdateView.as_view(), name='address-update'),
    path('address/<int:pk>/delete/', views.DeleteAddress.as_view(), name='address-delete'),
    path('address/', views.get_user_addresses, name='user-addresses'),
    path('<str:slug>/staff/', views.StaffDashboard.as_view(), name='staff-panel'),
    path('redirects/', views.login_redirects, name='redirects'),
    path('<str:slug>/panel/', views.CustomerPanel.as_view(), name='customer-panel'),
    path('<str:slug>/edit/', views.CustomerUpdateView.as_view(), name='customer-edit'),

    # API urls:
    # path('api/login/', API_views.LoginAPIView, name='login_api')
]

src/books/urls.py
from django.urls import path

from books import views
# from books.API_views import BookListAPIView, search


urlpatterns = [
    # path('API/book-list/', BookListAPIView.as_view(), name='API-books'),
    path('search/', views.Search.as_view(), name='search'),
    # path('search/', search, name='search'),
    path('<str:slug>/detail/', views.BookDetail.as_view(), name='detail'),
    path('new-book/', views.CreateBook.as_view(), name='create-book'),
    path('book-list/', views.BookList.as_view(), name='book-list'),
    path('<str:slug>/delete/', views.DeleteBookView.as_view(), name='delete-book'),
    path('<str:slug>/edit/', views.EditBook.as_view(), name='edit-book'),
    path('categories/', views.CategoryView.as_view(), name='categories'),
    path('categories/new/', views.CreateCategory.as_view(), name='new-category'),
    path('categories/<str:slug>/delete/', views.DeleteCategoryView.as_view(), name='delete-category'),
    path('categories/<str:slug>/edit/', views.EditCategoryView.as_view(), name='edit-category'),
    path('categories/<str:slug>/detail/', views.CategoryDetail.as_view(), name='category_detail'),
]

src/templates/_base.html
<!doctype html>
{% load static %}
{% load jalali_tags %}
<html lang="fa" dir="rtl">
<head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.rtl.min.css"
          integrity="sha384-gXt9imSW0VcJVHezoNQsP+TNrjYXoGcrqBZJpry9zJt8PCQjobwmhMGaDHTASo9N" crossorigin="anonymous">
    {% block csses %}{% endblock %}
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <link rel="stylesheet" href="{% static 'css/iziToast.min.css' %}">
    {#    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}"> <!-- bootstrap modal forms -->#}
    <link rel="stylesheet" href="{% static 'css/all.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block styles %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body style="  font-family: 'Vazir', Arial, Helvetica, sans-serif;line-height: 1.7em;background-color: #264b5d">
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}"><img class="w-75" src="{% static 'images/picture2.svg' %}"
                                                             alt=""></a>
        {% if user.is_authenticated %}
            <a class="btn" href="{% url 'last-order' %}">
                {% with total_qty=item_cnt %}
                    <span id="item-cnt" class="px-1 rounded" style="background-color: hotpink">
                    {% if total_qty > 0 %}
                        {{ total_qty }}
                    {% else %}
                        0
                    {% endif %}
                </span>
                {% endwith %}
                <i class="fas fa-cart-plus fa-2x" style="color: deeppink"></i></a>
        {% else %}
            <a class="btn" href="{% url 'summary' %}">
                {% with total_qty=basket|length %}
                    <span id="item-cnt" class="px-1 rounded" style="background-color: hotpink">
                    {% if total_qty > 0 %}
                        {{ total_qty }}
                    {% else %}
                        0
                    {% endif %}
                </span>
                {% endwith %}
                <i class="fas fa-cart-plus fa-2x" style="color: deeppink"></i></a>
        {% endif %}
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
                aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll d-flex align-items-center"
                style="--bs-scroll-height: 100px;">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'contact' %}">تماس باما</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'about' %}">درباره ما</a>
                </li>
                {% if user.is_staff %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'create-book' %}">کتاب جدید</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'new-category' %}">دسته جدید</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'all-discount-cods' %}">کدهای تخفیف</a>
                    </li>
                {% endif %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        دسته ها
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'categories' %}">همه دسته ها</a>
                        </li>
                        {% for cat in categories %}
                            <li><a class="dropdown-item" href="{% url 'category_detail' cat.slug %}">{{ cat.name }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    {% if user.is_authenticated %}
                        <a class="nav-link" href="#" id="navbarScrollingDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            {% if not user.is_superuser and user.is_staff %}
                                <i class="fas fas fa-user-tie fa-2x" style="color: lightgreen"><span
                                        style="font-size: 1rem;"> {{ user.first_name }} </span></i>

                            {% elif user.is_superuser and user.is_staff %}
                                <i class="fas fas fas fa-user-tie fa-2x" style="color: green"><span
                                        style="font-size: 1rem;"> {{ user.first_name }} </span></i>
                            {% else %}
                                <i class="fas fas fa-user-alt fa-2x">
                                    <span style="font-size: 1rem;"> {{ user.first_name }} </span></i></a>
                            {% endif %}
                        <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
                            <li><a class="dropdown-item" href="{% url 'account_change_password' %}">تغییر رمز عبور</a>
                            </li>
                            <li><a class="dropdown-item" href="{% url 'all-basket-orders' default_basket.pk %}">همه
                                سفارشات</a></li>
                            {% if user.is_superuser %}
                                <li><a class="dropdown-item" href="{% url 'admin:index' %}">پنل ادمین</a></li>
                                <li><a class="dropdown-item" href="{% url 'accounts:staff-panel' user.slug %}">پنل
                                    کارمند</a></li>
                            {% elif user.is_staff %}
                                <li><a class="dropdown-item" href="{% url 'accounts:staff-panel' user.slug %}">پنل
                                    کارمند</a></li>

                            {% endif %}
                            <li><a class="dropdown-item" href="{% url 'accounts:customer-panel' user.slug %}">پنل
                                مشتری</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="{% url 'account_logout' %}">خروج</a></li>
                        </ul>
                    {% else %}
                        <a class="nav-link dropdown-toggle" href="#" id="navbarScrollingDropdown" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false"> حساب کاربری
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarScrollingDropdown">
                            <li><a class="dropdown-item" href="{% url 'account_login' %}">ورود</a></li>
                            <li><a class="dropdown-item" href="{% url 'account_reset_password' %}">بازیابی رمز</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="{% url 'account_signup' %}">ثبت نام</a></li>
                            {#                    <li><a class="dropdown-item" href="{% url 'socialaccount_connections' %}">شبکه های اجتماعی</a></li>#}
                        </ul>
                    {% endif %}
                    </a>
                </li>
            </ul>
            <form id="srch" class="d-flex" action="{% url 'search' %}" method="get">
                <input id="srchContent" class="form-control me-2"
                       type="search" placeholder="عنوان یا نام نویسنده" aria-label="Search" name="query">
                <button class="btn btn-outline-success" type="submit">جستجو</button>
            </form>
        </div>
    </div>
</nav>

{% block content %}{% endblock %}

<footer class="bg-light text-center text-white footer mt-5">
    <!-- Grid container -->
    <div class="container p-4 pb-0">
        <!-- Section: Social media -->
        <section class="mb-4">
            <!-- telegram -->
            <a
                    class="btn btn-primary btn-floating m-1"
                    style="background-color: #3b5998;"
                    href="#!"
                    role="button"
            ><i class="fab fa-telegram"></i
            ></a>

            <!-- whatsapp -->
            <a
                    class="btn btn-primary btn-floating m-1"
                    style="background-color: #55acee;"
                    href="#!"
                    role="button"
            ><i class="fab fa-whatsapp"></i
            ></a>

            <!-- Google -->
            <a
                    class="btn btn-primary btn-floating m-1"
                    style="background-color: #dd4b39;"
                    href="#"
                    role="button"
            ><i class="fab fa-google"></i
            ></a>

            <!-- Linkedin -->
            <a
                    class="btn btn-primary btn-floating m-1"
                    style="background-color: #0082ca;"
                    href="#!"
                    role="button"
            ><i class="fab fa-linkedin-in"></i
            ></a>
            <!-- Github -->
            <a
                    class="btn btn-primary btn-floating m-1"
                    style="background-color: #333333;"
                    href="https://github.com/FatemehRahmanzadeh/Book_store_Rahmanzadeh"
                    role="button"
            ><i class="fab fa-github"></i
            ></a>
        </section>
        <!-- Section: Social media -->
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        © 2021 Copyright:
        <a class="text-white" href="#">bookstore</a>
    </div>
    <!-- Copyright -->
</footer>

<script src="{% static 'js/iziToast.min.js' %}" type="text/javascript"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/gh/xcash/bootstrap-autocomplete@v2.3.7/dist/latest/bootstrap-autocomplete.min.js"></script>
<script src="{% static 'js/scripts.js' %}" type="text/javascript"></script>
<!-- bootstrap modal form requirements:-->
<script src="{% static 'js/jquery.bootstrap.modal.forms.min.js' %}"></script>
<!-- By default, Datepicker using jQuery, you need to set your script after loading jQuery! -->
	<!-- loading directly -->
		<link rel="stylesheet" href="{% static 'admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css' %}">
		<script src="{% static 'admin/js/django_jalali.min.js' %}"></script>
	<!-- OR -->
	<!-- loading by form (if used AdminJalaliDateWidget) -->
		{{ form.media }}
</body>
</html>

src/templates/about.html
{% extends '_base.html' %}
{% block title %} درباره ما {% endblock %}
{% block content %}
    <section></section>
{% endblock %}

src/templates/book-detail.html
{% extends '_base.html' %}
{% block title %}جزییات {{ object.title }} {% endblock %}

{% block content %}

{% endblock %}

src/templates/contact.html
{% extends '_base.html' %}
{% block title %} تماس با ما {% endblock %}

src/templates/home.html
{% extends './_base.html' %}
{% block title %} خانه {% endblock %}
{% block content %}
    <h1 class="text-light my-3 text-center">به فروشگاه آنلاین کتاب خوش آمدید</h1>
    <section class="container" style="background-color: #ddffdd">
        <div class="row justify-content-evenly" style="background-color: darkcyan;">
            {% for book in books %}
                <div class="col-4 card my-5 mx-2" style="width: 14rem;">
                    <img src="{{ book.image.url }}" class="card-img-top" style="height:220px;" alt="{{ book.title }}">
                    <div class="card-body">
                        <p class="card-text desc">{{ book.description }}</p>
                        <a href="{% url 'detail' book.slug %}" class="btn btn-success">جزییات بیشتر</a>
                    </div>
                </div>

            {% endfor %}
        </div>

        <script>
            $(".desc").text(function (i, currentText) {
                return currentText.substring(0, 50)+ "...";
            });
        </script>

    </section>
{% endblock %}

src/templates/modal.html
<div class="modal fade" id="create-modal" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog mt-5">
    <div class="modal-content">
    </div>
  </div>
</div>

<div class="modal fade" tabindex="-1" role="dialog" id="modal">
  <div class="modal-dialog mt-5" role="document">
    <div class="modal-content"></div>
  </div>
</div>

src/templates/search.html
{% extends '_base.html' %}
{% load static %}
{% block styles %}
    <link rel="stylesheet" href="{% static 'css/search.css' %}">
{% endblock %}
{% block title %}نتایج جستجو {% endblock %}

{% block content %}
    <div class="container">
            <table class="table table-hover m-auto mt-5 text-center">
                  <tbody>
                    {% for book in object_list %}

                            <tr>
                            <td>
                                <div class="card mb-3">
                                      <div class="row g-0">
                                        <div class="col-md-4">
                                            {% if book.image %}
                                                <a href="{% url 'detail' book.slug %}"><img src="{{ book.image.url }}" class="img-fluid rounded-start" alt="..."></a>
                                            {% else %}
                                                <img src="{% static 'images/images.png' %}" class="img-fluid rounded-start" alt="...">
                                            {% endif %}
                                        </div>
                                        <div class="col-md-8">
                                          <div class="card-body">
                                            <h5 class="card-title"><a href="{% url 'detail' book.slug %}"><span id="title-a">{{ book.title }}</span></a></h5>
                                            <p class="card-text">اثر:
                                                <br>{{ book.authors }}</p>
                                              <br>
                                              <p>قیمت: <del class="text-muted" >{{ book.price }}</del> <b>{{ book.get_final_price }}</b></p>
                                              <p class="card-text"><small class="text-muted">آخرین بروز رسانی: {{ book.updated_at }}</small></p>
                                          </div>
                                        </div>
                                      </div>
                                </div>
                                </td>
                                <td>
                                    <div class="card mb-3 row">
                                            <div class=" col-12 row align-items-center my-3">
                                                <label class=" col-6 text-end me-3" for="num">تعداد: </label>
                                            <input class="col-4" id="num" type="number" min="1" step="1" max="{{ book.quantity }}">
                                            </div>
                                            <div class="col-12 my-5">
                                                <a href="" class="btn btn-success text-white" data-abc="true"> اضافه به سبد</a>
                                            </div>
                                    </div>
                                </td>
                            </tr>
                    {% endfor %}
                  </tbody>
    </table>
    </div>
{% endblock %}