src/BookStore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')),
    path('books/', include('books.urls')),
    path('orders/', include('orders.urls')),
    path('session/', include('session_basket.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('', include('pages.urls')),
    path('api/v1/dj-rest-auth/', include('dj_rest_auth.urls')),
    path('api/v1/dj-rest-auth/registration/', include('dj_rest_auth.registration.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.MEDIA_ROOT)

src/accounts/urls.py
from django.urls import path

from accounts import views, API_views

app_name = 'accounts'
urlpatterns = [
    path('signup/', views.SignUpView.as_view(), name='signup-modal'),
    path('address/create/', views.AddressCreateView.as_view(), name='address-create'),
    path('address/<int:pk>/update/', views.AddressUpdateView.as_view(), name='address-update'),
    path('address/<int:pk>/delete/', views.DeleteAddress.as_view(), name='address-delete'),
    path('address/', views.get_user_addresses, name='user-addresses'),
    path('<str:slug>/staff/', views.StaffDashboard.as_view(), name='staff-panel'),
    path('redirects/', views.login_redirects, name='redirects'),
    path('<str:slug>/panel/', views.CustomerPanel.as_view(), name='customer-panel'),
    path('<str:slug>/edit/', views.CustomerUpdateView.as_view(), name='customer-edit'),

    # API urls:
    # path('api/login/', API_views.LoginAPIView, name='login_api')
]

src/books/urls.py
from django.urls import path

from books import views
# from books.API_views import BookListAPIView, search


urlpatterns = [
    # path('API/book-list/', BookListAPIView.as_view(), name='API-books'),
    path('search/', views.Search.as_view(), name='search'),
    # path('search/', search, name='search'),
    path('<str:slug>/detail/', views.BookDetail.as_view(), name='detail'),
    path('new-book/', views.CreateBook.as_view(), name='create-book'),
    path('book-list/', views.BookList.as_view(), name='book-list'),
    path('<str:slug>/delete/', views.DeleteBookView.as_view(), name='delete-book'),
    path('<str:slug>/edit/', views.EditBook.as_view(), name='edit-book'),
    path('categories/', views.CategoryView.as_view(), name='categories'),
    path('categories/new/', views.CreateCategory.as_view(), name='new-category'),
    path('categories/<str:slug>/delete/', views.DeleteCategoryView.as_view(), name='delete-category'),
    path('categories/<str:slug>/edit/', views.EditCategoryView.as_view(), name='edit-category'),
    path('categories/<str:slug>/detail/', views.CategoryDetail.as_view(), name='category_detail'),
]

src/orders/urls.py
# from rest_framework import routers
#
# from orders.views import OrderViewSet

# router = routers.DefaultRouter()
# router.register('create_order', OrderViewSet, basename='create_order')
# urlpatterns = router.urls
from django.urls import path
from django.views.generic import TemplateView

from orders import discount_views
from orders.views import OrderRegister, create, last_uncheck_orders, CustomerOrderHistory, OrderDetail, OrderDelete, \
    RegisteredList, UnRegisteredList

urlpatterns = [
    path('create-order/', create, name='create-order'),
    path('<int:pk>/send-order/', OrderRegister.as_view(), name='order-send'),
    path('last-order/', last_uncheck_orders, name='last-order'),
    path('<int:pk>/detail/', OrderDetail.as_view(), name='order-detail'),
    path('<int:pk>/delete/', OrderDelete.as_view(), name='order-delete'),
    path('basket/<int:pk>/', CustomerOrderHistory.as_view(), name='all-basket-orders'),
    path('all-orders/registered/', RegisteredList.as_view(), name='all-reg-orders'),
    path('all-orders/unregistered/', UnRegisteredList.as_view(), name='all-not-reg-orders'),
    # تخفیف ها
    path('discounts/cods/', discount_views.DiscountCodeList.as_view(), name='all-discount-cods'),
    path('discounts/create/code/', discount_views.CreateDiscountCode.as_view(), name='create-code'),
    path('discounts/code/<int:pk>/edit/', discount_views.EditDiscountCode.as_view(), name='edit-code'),
    path('discounts/code/<int:pk>/delete/', discount_views.DeleteDiscountCode.as_view(), name='delete-code'),
    path('discounts/percent/', discount_views.PercentOffList.as_view(), name='all-discount-percents'),
    path('discounts/create/percent/', discount_views.CreatePercentOff.as_view(), name='create-percent'),
    path('discounts/percent/<int:pk>/edit/', discount_views.EditPercentOff.as_view(), name='edit-percent'),
    path('discounts/percent/<int:pk>/delete/', discount_views.DeletePercentOff.as_view(), name='delete-percent'),
    path('discounts/cash/', discount_views.CashOffList.as_view(), name='all-discount-cash'),
    path('discounts/create/cash/', discount_views.CreateCashOff.as_view(), name='create-cash'),
    path('discounts/cash/<int:pk>/edit/', discount_views.EditCashOff.as_view(), name='edit-cash'),
    path('discounts/cash/<int:pk>/delete/', discount_views.DeleteCashOff.as_view(), name='delete-cash'),
]

src/payments/urls.py
from django.urls import path

from payments import views
# from payments.views import OrderSummary


urlpatterns = [
    # path('order-summary/', OrderSummary.as_view(), name='summary'),
    path('add-to-basket/', views.add_to_basket, name='add_to_basket'),
    path('baske-summary/', views.basket_summary, name='summary'),
    path('delete-from-basket/', views.basket_delete, name='delete'),
    path('update-basket/', views.basket_update, name='update'),
]

src/orders/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone


class DiscountCode(models.Model):
    STATUS = [('E', 'منقضی شده'), ('V', 'معتبر')]
    TYPE = [('Ch', 'نقدی'), ('P', 'درصدی')]
    title = models.CharField(verbose_name='عنوان', max_length=100, unique=True)
    type = models.CharField(verbose_name='نوع', max_length=2, choices=TYPE)
    creator = models.ForeignKey(get_user_model(),
                                verbose_name='ایجادکننده',
                                on_delete=models.DO_NOTHING,
                                related_name='disObj_registrar')
    last_edited_by = models.ForeignKey(get_user_model(),
                                       verbose_name='آخرین ویرایش توسط',
                                       related_name='disObj_editor',
                                       on_delete=models.DO_NOTHING, null=True, blank=True)
    percent_off = models.IntegerField(verbose_name='مقدار درصدی', blank=True, null=True)
    cash_off = models.IntegerField(verbose_name='مقدار نقدی', blank=True, null=True)
    min_price_off = models.BigIntegerField('حداقل قیمت')
    code = models.CharField(verbose_name='کد تخفیف', max_length=100, blank=True, null=True)
    start = models.DateTimeField(verbose_name='زمان شروع', blank=True, null=True)
    end = models.DateTimeField(verbose_name='زمان پایان', blank=True, null=True)
    status = models.CharField(verbose_name='وضعیت', max_length=2, choices=STATUS, default='')

    class Meta:
        ordering = ['end']
        verbose_name = 'تخفیف کددار'
        verbose_name_plural = 'تخفیف های کددار'

    def __str__(self):
        return f'{self.title} تا  {self.end} فعال است'

    def discount_is_valid(self):
        """
        بررسی تخفیف از نظر اوضعیت اعتبار و زمان انقضا
        """
        if self.status == 'E' or self.end <= timezone.now():
            return False

        else:
            return True

    def get_absolute_url(self):
        return "/orders/discounts/%i/" % self.pk

    def add_order(self, order, user):
        """
        اعمال تخفیف به سفارش.
        :return: اگز تخفیف مجاز بود سفارش به لیست سفارشات این تخفیف اضافه می شود و 1 برمیگرداند.
        اگر تخفیف از نظر زمان و یا فعال بودن معتبر نبود 3 برمیگرداند
        اگر مبلغ سفارش از حداقل مبلغ شامل تخفیف کمتر بود 2 بر می گرداند
        """
        if self.discount_is_valid():
            if order.get_order_price() >= self.min_price_off:
                user_orders = user.customer_basket.basket_orders.all().filter(discount__isnull=False)
                user_discs = [_.discount.id for _ in user_orders]
                if self.id in user_discs:
                    return 0
                self.discount_orders.add(order)
                self.save()
                return 1
            else:
                return 2
        else:
            return 3


class PercentOff(models.Model):
    STATUS = [('E', 'منقضی شده'), ('V', 'معتبر')]
    title = models.CharField(verbose_name='عنوان', max_length=100)
    creator = models.ForeignKey(get_user_model(), verbose_name='ایجادکننده', on_delete=models.DO_NOTHING,
                                related_name='percent_registrar')
    last_edited_by = models.ForeignKey(get_user_model(),
                                       verbose_name='آخرین ویرایش توسط',
                                       related_name='percent_editor',
                                       on_delete=models.DO_NOTHING, null=True, blank=True)
    percent_off = models.IntegerField(verbose_name='مقدار درصدی', blank=True, null=True)
    start = models.DateTimeField(verbose_name='زمان شروع', blank=True, null=True)
    end = models.DateTimeField(verbose_name='زمان پایان', blank=True, null=True)
    status = models.CharField(verbose_name='وضعیت', max_length=2, choices=STATUS, default='')

    class Meta:
        verbose_name = 'تخفیف درصدی'
        verbose_name_plural = 'تخفیف های درصدی'

    def __str__(self):
        return f'{self.title} ({self.percent_off}%)'

    def get_absolute_url(self):
        return "/orders/discounts/%i/" % self.pk


class CashOff(models.Model):
    STATUS = [('E', 'منقضی شده'), ('V', 'معتبر')]
    title = models.CharField(verbose_name='عنوان', max_length=100)
    creator = models.ForeignKey(get_user_model(), verbose_name='ایجادکننده', on_delete=models.DO_NOTHING,
                                related_name='cash_registrar')
    last_edited_by = models.ForeignKey(get_user_model(),
                                       verbose_name='آخرین ویرایش توسط',
                                       related_name='cash_editor',
                                       on_delete=models.DO_NOTHING, null=True, blank=True)
    cash_off = models.IntegerField(verbose_name='مقدار نقدی', blank=True, null=True)
    min_price_off = models.BigIntegerField('حداقل قیمت')
    start = models.DateTimeField(verbose_name='زمان شروع', blank=True, null=True)
    end = models.DateTimeField(verbose_name='زمان پایان', blank=True, null=True)
    status = models.CharField(verbose_name='وضعیت', max_length=2, choices=STATUS, default='')

    class Meta:
        verbose_name = 'تخفیف نقدی'
        verbose_name_plural = 'تخفیف های نقدی'

    def __str__(self):
        return f'{self.title} ({self.cash_off}تومان)'

    def get_absolute_url(self):
        return "/orders/discounts/%i/" % self.pk


class DefaultBasket(models.Model):
    """
    این سبد خرید مشتری بعد از لاگین است که رفتارهای مشتری در سایت را مدیریت میکند. مثل افزودن و حذف کالا از سفارش،
    """
    customer = models.OneToOneField(get_user_model(),
                                    verbose_name='مشتری',
                                    on_delete=models.DO_NOTHING,
                                    related_name='customer_basket')

    class Meta:
        verbose_name = 'سبد خرید مشتری'
        verbose_name_plural = 'سبدهای خرید مشتریان'

    def __str__(self):
        return f'{self.customer.email}'

    def get_registered_orders(self):
        """
        فیلتر سفارشات بر اساس وضعیت ثبت شده
        """
        return self.basket_orders.filter(status='R')

    def get_ordered_orders(self):
        """
        فیلتر سفارشات سبد خرید بر اساس وضعیت ثبت نشده
        """
        return self.basket_orders.filter(status='O')

    def add(self, book, qty):
        book_id = book.id
        current_order = self.basket_orders.filter(status='O').last()
        if current_order:
            items = current_order.order_items.all()

            if book_id in [b.book.id for b in items]:
                item = items.get(book__id=book_id)
                item.quantity = qty
                item.save()
            else:
                OrderItem.objects.create(order=current_order, book=book, quantity=qty)
            return current_order
        else:
            new_order = Order.objects.create(basket=self)
            OrderItem.objects.create(order=new_order, book=book, quantity=qty)
            return new_order

    def update(self, item, qty):
        """
        اعمال تغییر در تعداد آیتم انتخابی با زدن دکمه بروزرسانی در سبد خرید.
        """
        current_order = self.basket_orders.filter(status='O').last()
        item = current_order.order_items.all().get(id=item)
        item.quantity = qty
        item.save()
        return current_order

    def delete_item(self, item_id):
        """
        حذف آیتم انتخابی از سبد خرید و سفارش
        """
        current_order = self.basket_orders.get(order_items__id=item_id)
        item = current_order.order_items.all().get(id=item_id)
        if item:
            item.delete()
        return current_order

    def get_absolute_url(self):
        return "/orders/basket/%i/" % self.pk


class Order(models.Model):
    STATUS = [('R', 'ثبت شده'), ('O', 'سفارش'), ('D', 'تحویل')]

    created_at = models.DateTimeField(verbose_name='زمان ایجاد', auto_now_add=True)
    discount = models.ForeignKey(DiscountCode, verbose_name='تخفیف',
                                 on_delete=models.DO_NOTHING,
                                 related_name='discount_orders',
                                 blank=True, null=True)
    delivery_address = models.ForeignKey('accounts.Address',
                                         verbose_name='آدرس سفارش',
                                         on_delete=models.DO_NOTHING,
                                         related_name='order_addresses', blank=True, null=True)
    status = models.CharField(verbose_name='وضعیت سفارش', max_length=2, choices=STATUS, default='O')
    basket = models.ForeignKey(DefaultBasket, verbose_name='سبد خرید',
                               on_delete=models.DO_NOTHING,
                               related_name='basket_orders')

    class Meta:
        verbose_name = 'سفارش'
        verbose_name_plural = 'سفارش های مشتریان'

    def get_absolute_url(self):
        return "/orders/%i/" % self.pk

    def get_order_price(self):
        order_price = sum(_.get_item_price() for _ in self.order_items.all())
        print('order price model', order_price)
        if self.discount:
            if self.discount.type == 'Ch' and order_price >= self.discount.min_price_off:
                order_price -= self.discount.cash_off

            elif self.discount.type == 'P':
                order_price *= (100 - self.discount.percent_off) / 100

        return order_price

    def __str__(self):
        return f'سفارش مربوط به {self.basket.customer.email}'


class OrderItem(models.Model):
    """
    مدل مربوط به اقلام سفارش مشتری. هر مورد دارای یک کتاب و تعداد آن است. به عبارتی اگر سفارش را یک جدول فرض کنیم
    ، آبجکت های این کلاس سطرهای آن جدول را تشکیل می دهند.
    """
    book = models.ForeignKey('books.Book', verbose_name='کتاب', on_delete=models.DO_NOTHING, related_name='orders')
    order = models.ForeignKey(Order, verbose_name='سفارش مربوطه', on_delete=models.CASCADE,
                              related_name='order_items')
    quantity = models.IntegerField(verbose_name='تعداد', default=1)

src/payments/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render
# from django.views.generic import ListView

from books.models import Book
# from payments.models import Order
from payments.shopping_basket import Basket as SBasket


# class OrderSummary(ListView):
#     model = Order
#     template_name = 'payments/orders/summary.html'
#
#

def basket_summary(request):
    basket = SBasket(request)
    return render(request, 'payments/orders/summary.html', {'basket':basket})


def add_to_basket(request):
    basket = SBasket(request)
    if request.POST.get('action') == 'post':
        book_id = int(request.POST.get('book_id'))
        book_qty = int(request.POST.get('book_qty'))
        book = get_object_or_404(Book, id=book_id)
        basket.add(book=book, qty=book_qty)
        if book.quantity == 0:
            text_msg = 'متاسفانه درحال حاضر کتاب موجود نیست '
            status = 0
        else:
            basket.add(book=book, qty=book_qty)
            status = 1
            text_msg = 'کتاب با موفقیت به سبد اضافه شد'
        basket_qty = basket.__len__()
        response = JsonResponse({'qty': basket_qty, 'text_msg': text_msg, 's': status})
        return response


def basket_delete(request):
    basket = SBasket(request)
    if request.POST.get('action') == 'post':
        book_id = int(request.POST.get('book_id'))
        basket.delete(book=book_id)

        basket_qty = basket.__len__()
        basket_total = basket.get_total_price()
        response = JsonResponse({'qty': basket_qty, 'total': basket_total})
        return response


def basket_update(request):
    basket = SBasket(request)
    if request.POST.get('action') == 'post':
        book_id = int(request.POST.get('book_id'))
        book_qty = int(request.POST.get('book_qty'))
        basket.update(book=book_id, qty=book_qty)

        basket_qty = basket.__len__()
        basket_total = basket.get_total_price()
        response = JsonResponse({'qty': basket_qty, 'total': basket_total})
        return response

src/templates/payments/orders/all_customer_orders.html
{% extends '_base.html' %}
{% block title %}تاریخچه سفارشات{% endblock %}
{% block content %}
    <main class="container mx-auto mt-3">
        <section class="container">
            <h3><span class="bg-light text-success m-2 px-3 py-2">سفارشات ثبت شده</span></h3>
            <div class="row  border rounded align-items-center my-3">
                {% for order in registered %}
                    <div class="col-12 bg-light m-2">
                        <h5>
                            وضعیت سفارش: {{ order.get_status_display }} |
                            <span style="font-size: smaller" class="text-muted">تاریخ: {{ order.created_at }}</span>
                        </h5>
                        <div class="container">
                            <div class="border rounded row justify-content-start">
                                {% for item in order.order_items.all %}
                                    <div class="col-6 col-md-2 card">
                                        <a class="col text-decoration-none" href="{% url 'detail' item.book.slug %}">
                                            <img class="card-img-top" style="width:100px"
                                                 src="{{ item.book.image.url }}"
                                                 alt="{{ item.book.title }}">
                                        </a>
                                        <div class="card-body">
                                            <h5 class="card-title">{{ item.book.title }}</h5>
                                        </div>
                                        <ul class="list-group list-group-flush">
                                            <li class="list-group-item">تعداد: {{ item.quantity }} </li>
                                            <li class="list-group-item">قیمت تمام شده: {{ item.get_item_price }}تومان
                                            </li>
                                            <li class="list-group-item">
                                                تخفیف کل مورد:
                                                {% if item.book.percent_off %}
                                                    {{ item.book.percent_off.percent_off }} درصد
                                                {% elif item.book.max_cash_off %}
                                                    {% widthratio item.book.max_cash_off.cash_off 1 item.quantity %}
                                                    تومان
                                                {% else %}
                                                    تخفیف ندارد
                                                {% endif %}
                                            </li>
                                        </ul>
                                    </div>
                                {% endfor %}

                            </div>
                        </div>
                        <div class="row my-3">
                            <h5 class="col-md-3">قیمت کل سفارش: {{ order.get_order_price }}</h5>
                            {% if order.discount %}

                                <h5 class="col-md-3">
                                    {% if order.discount.percent_off %}
                                        درصد تخفیف سفارش: {{ order.discount.percent_off }}%
                                    {% elif order.discount.cash_off %}
                                        مبلغ تخفیف سفارش: {{ order.discount.cash_off }} تومان
                                        </h5>
                                    {% endif %}

                            {% endif %}

                        </div>
                    </div>
                {% endfor %}

            </div>

        </section>
        <section class="container mt-5 mx-auto">

            <h3><span class="bg-warning m-2 px-3 py-2">سفارشات نهایی نشده</span></h3>
            <div class="row my-3">
                {% for order in ordered %}
                    <div class="col-12 bg-light m-2">
                        <h5>
                            وضعیت سفارش: {{ order.get_status_display }} |
                            <span style="font-size: smaller" class="text-muted">تاریخ: {{ order.created_at }}</span>
                        </h5>
                        <div class="container">
                            <div class="border rounded row justify-content-start">
                                {% for item in order.order_items.all %}
                                    <div class="col-6 col-md-2 card">
                                        <a class="col text-decoration-none" href="{% url 'detail' item.book.slug %}">
                                            <img class="card-img-top" style="width:100px"
                                                 src="{{ item.book.image.url }}"
                                                 alt="{{ item.book.title }}">
                                        </a>
                                        <div class="card-body">
                                            <h5 class="card-title">{{ item.book.title }}</h5>
                                        </div>
                                        <ul class="list-group list-group-flush">
                                            <li class="list-group-item">تعداد: {{ item.quantity }} </li>
                                            <li class="list-group-item">قیمت تمام شده: {{ item.get_item_price }}تومان
                                            </li>
                                            <li class="list-group-item">
                                                تخفیف کل مورد:
                                                {% if item.book.percent_off %}
                                                    {{ item.book.percent_off.percent_off }} درصد
                                                {% elif item.book.max_cash_off %}
                                                    {% widthratio item.book.max_cash_off.cash_off 1 item.quantity %}
                                                    تومان
                                                {% else %}
                                                    تخفیف ندارد
                                                {% endif %}
                                            </li>
                                        </ul>
                                    </div>
                                {% endfor %}

                            </div>
                        </div>
                        <div>
                            <a role="button" class="btn btn-success m-3" href="{% url 'order-send' order.pk %}">تکمیل
                                سفارش</a>
                            <a role="button" class="btn btn-primary m-3" href="{% url 'order-detail' order.pk %}">جزئیات
                                سفارش</a>
                            <a role="button" class="btn btn-danger m-3" href="{% url 'order-delete' order.pk %}">حذف
                                سفارش</a>
                        </div>
                    </div>
                {% endfor %}

            </div>

        </section>
    </main>
{% endblock %}

src/templates/payments/orders/all_not_reg_orders.html
{% extends '_base.html' %}
{% block title %}همه سفارشات ثبت شده{% endblock %}
{% block content %}
    <section class="container mt-5 mx-auto">

        <h3><span class="bg-warning m-2 px-3 py-2">سفارشات نهایی نشده</span></h3>
        <div class="row my-3">
            {% for order in all_ordered %}
                <div class="col-12 bg-light m-2">
                    <h5>
                        وضعیت سفارش: {{ order.get_status_display }} |
                        <span style="font-size: smaller" class="text-muted">تاریخ: {{ order.created_at }}</span> |
                        <span style="font-size: smaller" class="text-muted">{{ order.basket.customer.email }}</span>
                    </h5>
                    <div class="container">
                        <div class="border rounded row justify-content-start">
                            {% for item in order.order_items.all %}

                                <div class="col-6 col-md-2 card">
                                    <a class="col text-decoration-none" href="{% url 'detail' item.book.slug %}">
                                        <img class="card-img-top" style="width:100px"
                                             src="{{ item.book.image.url }}"
                                             alt="{{ item.book.title }}">
                                    </a>
                                    <div class="card-body">
                                        <h5 class="card-title">{{ item.book.title }}</h5>
                                    </div>
                                    <ul class="list-group list-group-flush">
                                        <li class="list-group-item">تعداد: {{ item.quantity }} </li>
                                        <li class="list-group-item">قیمت تمام شده: {{ item.get_item_price }}تومان</li>
                                        <li class="list-group-item">
                                            تخفیف:
                                            {% if item.book.percent_off %}
                                                {{ item.book.percent_off.percent_off }} درصد
                                            {% elif item.book.max_cash_off %}
                                                {{ item.book.max_cash_off.cash_off }}تومان
                                            {% else %}
                                                تخفیف ندارد
                                            {% endif %}
                                        </li>
                                    </ul>
                                </div>
                            {% endfor %}

                        </div>
                    </div>
                    <h5 class="my-3">قیمت کل سفارش: {{ order.get_order_price }}</h5>
                </div>
            {% endfor %}

        </div>

    </section>
{% endblock %}

src/templates/payments/orders/order-finalize.html
{% extends '_base.html' %}
{% load static %}
{% block title %}تکمیل سفارش{% endblock %}
{% block content %}
    <section class="container mx-auto my-5 w-50" style="background-color:lightblue;border-radius:10px;">
        <div>
            <h3 class="text-center">تکمیل سفارش</h3>
            <div class="row justify-content-center align-items-center">
                <form method='POST' action='' enctype="multipart/form-data" novalidate id="book-form" class="col-8 m-5" method="post">
                    {% csrf_token %}
                    <h5 class="text-danger">{{ form.non_field_errors }}</h5>
                    <label for="book-author" class="control-label">آدرس:</label>
                    {{ form.delivery_address }}
                    <a href="{% url 'accounts:address-create' %}" id="add" onclick="return showAddPopup(this);">
                        <i class="fas fa-plus"></i>
                    </a>
{#                    {% if order.delivery_address %}:#}
{#                        <a href="{% url "accounts:address-update"%} order.delivery_address.pk %}" id="edit_addr"#}
{#                           style="cursor: pointer; cursor: hand;">#}
{#                            <i class="fas fa-edit"></i></a>#}
{#                    {% endif %}#}
                    <br><br>
                    <h5 class="text-danger">{{ form.discount.errors }}</h5>
                    <div>
                        <input id="disc-input" title="کدتخفیف" type="text" class="form-control" name="discount" placeholder="اگر کد تخفیف دارید وارد کنید">
                        <button id="disc_btn" data-url = {% url 'order-send' form.instance.id %} type="button"
                                data-order ='{{ form.instance.id }}'
                                class="btn btn-primary my-2">بررسی تخفیف</button>
                    </div>
                    <h5> مبلغ قابل پرداخت: <span id="total-price">{{ order.get_order_price }}</span></h5>
                    <br><br>
                    <button id="submit-order" type="submit" class="btn btn-success">تایید</button>
                </form>
            </div>
        </div>
    </section>

{% endblock %}

src/templates/payments/orders/order_delete.html
{% extends '_base.html' %}
{% block title %}حذف سفارش {{ object.basket }}{% endblock %}
{% block content %}
    <div class="container mx-auto">
        <div class="container mx-auto w-50 rounded my-5" style="background-color: #ddffdd">
            <form class="text-center p-3" action="" method="post">{% csrf_token %}
                <p>مطمئنی میخوای سفارش "{{ object.pk }}" رو حذف کنی؟</p>
                <button class="btn btn-danger ml-2" type="submit">تایید</button>
            </form>
        </div>
    </div>
{% endblock %}